name: Feature Request
description: Suggest a new feature or enhancement for Pawboard
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! We love hearing ideas to make Pawboard better.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Describe the problem you're trying to solve.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see.
      placeholder: I would like to be able to...
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What area does this feature relate to?
      options:
        - Cards (new card features, formatting, organization)
        - Canvas (navigation, layout, views)
        - Collaboration (real-time features, presence, communication)
        - Session Management (settings, permissions, moderation)
        - Export/Import (save, share, integrate)
        - Accessibility (a11y improvements)
        - Mobile Experience
        - AI Features
        - UI/UX Improvements
        - Integrations (third-party services)
        - Other
    validations:
      required: true

  - type: dropdown
    id: user-type
    attributes:
      label: Primary User Benefit
      description: Who would benefit most from this feature?
      options:
        - Solo users (personal brainstorming)
        - Small teams (2-5 people)
        - Large groups (6+ people)
        - Session creators/moderators
        - All users equally
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: I've tried to work around this by...

  - type: textarea
    id: mockups
    attributes:
      label: Mockups or Examples
      description: If you have mockups, sketches, or examples from other apps, share them here.
      placeholder: Drag and drop images or paste URLs...

  - type: dropdown
    id: priority
    attributes:
      label: How important is this feature to you?
      options:
        - Nice to have
        - Would significantly improve my experience
        - Critical for my use case
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, use cases, or information about the feature request.
      placeholder: Add any other context here...
